SCR_MissionHeaderCombatOps {
 World "{94C4DD35078D0368}Worlds/TestIncognito.ent"
 m_sName "ArgA Incognito"
 m_sAuthor "Vultur"
 m_sDescription "Incognito MOD"
 m_sDetails "Implement a stealth system that allows players to blend in by using enemy equipment."
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 6
 m_eSaveTypes 0
 m_aTaskTypesAvailable {
  SCR_ScenarioFrameworkTaskType "{65DAC994BEA06D17}" {
   m_eTypeOfTask DELIVER
  }
  SCR_ScenarioFrameworkTaskType "{65DAC994BEA06D15}" {
   m_eTypeOfTask DESTROY
  }
  SCR_ScenarioFrameworkTaskType "{65DAC994BEA049CF}" {
   m_eTypeOfTask CLEAR_AREA
  }
  SCR_ScenarioFrameworkTaskType "{65DAC994BEA049C9}" {
   m_eTypeOfTask KILL
  }
  SCR_ScenarioFrameworkTaskType "{65DAC994BEA04931}" {
   m_eTypeOfTask DEFEND
  }
 }
}